# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/mikhailisakov/BankDB/ReportWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportWindow(object):
    def setupUi(self, ReportWindow):
        ReportWindow.setObjectName("ReportWindow")
        ReportWindow.resize(798, 594)
        self.centralwidget = QtWidgets.QWidget(ReportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HeadingLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeadingLabel.setMinimumSize(QtCore.QSize(0, 50))
        self.HeadingLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.HeadingLabel.setObjectName("HeadingLabel")
        self.verticalLayout.addWidget(self.HeadingLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.TableView = QtWidgets.QTableView(self.centralwidget)
        self.TableView.setMinimumSize(QtCore.QSize(0, 0))
        self.TableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TableView.setObjectName("TableView")
        self.verticalLayout.addWidget(self.TableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BackPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackPushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.BackPushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.BackPushButton.setObjectName("BackPushButton")
        self.horizontalLayout.addWidget(self.BackPushButton)
        self.ExportPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExportPushButton.setMinimumSize(QtCore.QSize(250, 50))
        self.ExportPushButton.setMaximumSize(QtCore.QSize(300, 50))
        self.ExportPushButton.setObjectName("ExportPushButton")
        self.horizontalLayout.addWidget(self.ExportPushButton)
        self.QuitPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.QuitPushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.QuitPushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.QuitPushButton.setObjectName("QuitPushButton")
        self.horizontalLayout.addWidget(self.QuitPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        ReportWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ReportWindow)
        self.statusbar.setObjectName("statusbar")
        ReportWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ReportWindow)
        QtCore.QMetaObject.connectSlotsByName(ReportWindow)

    def retranslateUi(self, ReportWindow):
        _translate = QtCore.QCoreApplication.translate
        ReportWindow.setWindowTitle(_translate("ReportWindow", "Вывод отчета"))
        self.HeadingLabel.setText(_translate("ReportWindow", "Вывод отчета с заданными вами ранее параметрами"))
        self.BackPushButton.setText(_translate("ReportWindow", "Назад"))
        self.ExportPushButton.setText(_translate("ReportWindow", "Экспортировать в Ecxel"))
        self.QuitPushButton.setText(_translate("ReportWindow", "Выйти"))
