# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/mikhailisakov/BankDB/BankApp/BankListReportWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BankListReportWindow(object):
    def setupUi(self, BankListReportWindow):
        BankListReportWindow.setObjectName("BankListReportWindow")
        BankListReportWindow.resize(600, 470)
        BankListReportWindow.setMinimumSize(QtCore.QSize(600, 450))
        BankListReportWindow.setMaximumSize(QtCore.QSize(700, 470))
        self.centralwidget = QtWidgets.QWidget(BankListReportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HeadingLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeadingLabel.setMinimumSize(QtCore.QSize(200, 50))
        self.HeadingLabel.setObjectName("HeadingLabel")
        self.verticalLayout.addWidget(self.HeadingLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.StatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.StatusLabel.setMinimumSize(QtCore.QSize(0, 50))
        self.StatusLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.StatusLabel.setText("")
        self.StatusLabel.setObjectName("StatusLabel")
        self.verticalLayout.addWidget(self.StatusLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.DescriptionTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.DescriptionTextBrowser.setMinimumSize(QtCore.QSize(100, 0))
        self.DescriptionTextBrowser.setMaximumSize(QtCore.QSize(16777215, 150))
        self.DescriptionTextBrowser.setObjectName("DescriptionTextBrowser")
        self.verticalLayout.addWidget(self.DescriptionTextBrowser, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BankNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.BankNameLabel.setMinimumSize(QtCore.QSize(200, 50))
        self.BankNameLabel.setMaximumSize(QtCore.QSize(200, 50))
        self.BankNameLabel.setObjectName("BankNameLabel")
        self.horizontalLayout.addWidget(self.BankNameLabel)
        self.ListBankNameComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ListBankNameComboBox.setObjectName("ListBankNameComboBox")
        self.horizontalLayout.addWidget(self.ListBankNameComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DateLabel = QtWidgets.QLabel(self.centralwidget)
        self.DateLabel.setMinimumSize(QtCore.QSize(200, 50))
        self.DateLabel.setMaximumSize(QtCore.QSize(200, 50))
        self.DateLabel.setObjectName("DateLabel")
        self.horizontalLayout_2.addWidget(self.DateLabel)
        self.DateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.DateEdit.setMaximumDate(QtCore.QDate(2018, 12, 31))
        self.DateEdit.setMinimumDate(QtCore.QDate(2018, 1, 1))
        self.DateEdit.setObjectName("DateEdit")
        self.horizontalLayout_2.addWidget(self.DateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BackPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackPushButton.setMinimumSize(QtCore.QSize(200, 50))
        self.BackPushButton.setMaximumSize(QtCore.QSize(250, 50))
        self.BackPushButton.setObjectName("BackPushButton")
        self.horizontalLayout_3.addWidget(self.BackPushButton)
        self.FormPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.FormPushButton.setMinimumSize(QtCore.QSize(200, 50))
        self.FormPushButton.setMaximumSize(QtCore.QSize(250, 50))
        self.FormPushButton.setObjectName("FormPushButton")
        self.horizontalLayout_3.addWidget(self.FormPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        BankListReportWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BankListReportWindow)
        self.statusbar.setObjectName("statusbar")
        BankListReportWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BankListReportWindow)
        QtCore.QMetaObject.connectSlotsByName(BankListReportWindow)

    def retranslateUi(self, BankListReportWindow):
        _translate = QtCore.QCoreApplication.translate
        BankListReportWindow.setWindowTitle(_translate("BankListReportWindow", "Создание отчета для нескольких банков"))
        self.HeadingLabel.setText(_translate("BankListReportWindow", "Выберите параметры отчета"))
        self.DescriptionTextBrowser.setHtml(_translate("BankListReportWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Список возможных банков представлен ниже справа. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Можете выбрать несколько, в частности один или все.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Минимальная возможная дата: 01.01.2018.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Максимальная возможная дата: 31.12.2018.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.BankNameLabel.setText(_translate("BankListReportWindow", "Выберите названия банков:"))
        self.DateLabel.setText(_translate("BankListReportWindow", "Выберите дату отчета:"))
        self.DateEdit.setDisplayFormat(_translate("BankListReportWindow", "MM.yyyy"))
        self.BackPushButton.setText(_translate("BankListReportWindow", "Назад"))
        self.FormPushButton.setText(_translate("BankListReportWindow", "Сформировать отчет"))
