# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/mikhailisakov/BankDB/BankApp/ChooseReportWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseReportWindow(object):
    def setupUi(self, ChooseReportWindow):
        ChooseReportWindow.setObjectName("ChooseReportWindow")
        ChooseReportWindow.resize(451, 205)
        self.centralwidget = QtWidgets.QWidget(ChooseReportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HeadingLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeadingLabel.setMinimumSize(QtCore.QSize(0, 50))
        self.HeadingLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.HeadingLabel.setObjectName("HeadingLabel")
        self.verticalLayout.addWidget(self.HeadingLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BankPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.BankPushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.BankPushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.BankPushButton.setObjectName("BankPushButton")
        self.horizontalLayout.addWidget(self.BankPushButton, 0, QtCore.Qt.AlignTop)
        self.BankListPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.BankListPushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.BankListPushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.BankListPushButton.setObjectName("BankListPushButton")
        self.horizontalLayout.addWidget(self.BankListPushButton, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.BackPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackPushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.BackPushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.BackPushButton.setObjectName("BackPushButton")
        self.verticalLayout.addWidget(self.BackPushButton)
        ChooseReportWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ChooseReportWindow)
        self.statusbar.setObjectName("statusbar")
        ChooseReportWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChooseReportWindow)
        QtCore.QMetaObject.connectSlotsByName(ChooseReportWindow)

    def retranslateUi(self, ChooseReportWindow):
        _translate = QtCore.QCoreApplication.translate
        ChooseReportWindow.setWindowTitle(_translate("ChooseReportWindow", "Выбор формы отчета"))
        self.HeadingLabel.setText(_translate("ChooseReportWindow", "Выберите форму отчета"))
        self.BankPushButton.setText(_translate("ChooseReportWindow", "Отчет для одного банка"))
        self.BankListPushButton.setText(_translate("ChooseReportWindow", "Отчет для нескольких банков"))
        self.BackPushButton.setText(_translate("ChooseReportWindow", "Назад"))
