# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/mikhailisakov/BankDB/BankApp/AdminChooseSettingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminChooseSettingsWindow(object):
    def setupUi(self, AdminChooseSettingsWindow):
        AdminChooseSettingsWindow.setObjectName("AdminChooseSettingsWindow")
        AdminChooseSettingsWindow.resize(628, 233)
        self.centralwidget = QtWidgets.QWidget(AdminChooseSettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HeadingLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeadingLabel.setMinimumSize(QtCore.QSize(0, 50))
        self.HeadingLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.HeadingLabel.setObjectName("HeadingLabel")
        self.verticalLayout.addWidget(self.HeadingLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SettingsPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.SettingsPushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.SettingsPushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.SettingsPushButton.setObjectName("SettingsPushButton")
        self.horizontalLayout.addWidget(self.SettingsPushButton, 0, QtCore.Qt.AlignTop)
        self.BankPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.BankPushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.BankPushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.BankPushButton.setObjectName("BankPushButton")
        self.horizontalLayout.addWidget(self.BankPushButton, 0, QtCore.Qt.AlignTop)
        self.BankListPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.BankListPushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.BankListPushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.BankListPushButton.setObjectName("BankListPushButton")
        self.horizontalLayout.addWidget(self.BankListPushButton, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.BackPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackPushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.BackPushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.BackPushButton.setObjectName("BackPushButton")
        self.verticalLayout.addWidget(self.BackPushButton)
        AdminChooseSettingsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AdminChooseSettingsWindow)
        self.statusbar.setObjectName("statusbar")
        AdminChooseSettingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AdminChooseSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminChooseSettingsWindow)

    def retranslateUi(self, AdminChooseSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminChooseSettingsWindow.setWindowTitle(_translate("AdminChooseSettingsWindow", "Выбор настроек"))
        self.HeadingLabel.setText(_translate("AdminChooseSettingsWindow", "Выберите настройки"))
        self.SettingsPushButton.setText(_translate("AdminChooseSettingsWindow", "Изменить настройки"))
        self.BankPushButton.setText(_translate("AdminChooseSettingsWindow", "Отчет для одного банка"))
        self.BankListPushButton.setText(_translate("AdminChooseSettingsWindow", "Отчет для нескольких банков"))
        self.BackPushButton.setText(_translate("AdminChooseSettingsWindow", "Назад"))
